### ISSUE TITLE
Importing or adding database does not save properly after performance commit

### ISSUE THREAD

**Issue by FrozenAssassine** [FrozenAssassine/EasePass#144]
After merging #143 the import and creating of databases does not get saved. To reproduce this:

Go to manage database page -> click on import database -> select any database to import
-> enter your password into the dialog -> the database should be imported.

Now close the app and restart, you should already see that the database was not found, because in the login page should be nothing selected. I am not quite familiar with your new code, so would you mind taking a look again 💯 

@Flamifly

**Comment by Flamifly** [comment]
Yea I will take a Look again on that my bad sorry

**Comment by FrozenAssassine** [comment]
I already fixed it, was not too hard😃

**Comment by Flamifly** [comment]
Was my error that I forgot to do +1?

**Comment by Flamifly** [comment]
And btw do you understand why I did it this way and why it is a little bit better?
If not i can try to explain it to you

**Comment by FrozenAssassine** [comment]
So you forgot the +1 correct and also some little things, like the length less than 1024 not 1025. Also the indexing for the path in the for loop was wrong. But not a big deal. 
Actually, I am curious why you did it this way, maybe you could give a short explanation?

**Comment by Flamifly** [comment]
The 1025 was on purpose it's just that the Max size for the stack will be 1024

Do you know what Spans are?

**Comment by FrozenAssassine** [comment]
Oh, if it was correct with 1025, I will change it back

I actually never used spans, so no idea?

**Comment by Flamifly** [comment]
nah you don't have to change it back

**Comment by Flamifly** [comment]
So the first change that I made there is that I do not Split on the string.
If I would do Split on the String I would allocate a new string[] which can be inefficient and will allocate more space and will take some more time.

Instead I use a Span. A Span is a ValueType so it exist on the Stack and not on the Heap by that we won't allocate a new Array of string we will just allocate the String at the given Range (Performs slighty better in Performance and Allocation).

I have said that a Span exist on the Stack and not on the Heap but in this line we say if we do have more than 1023 paths we want to create a new Array of Ranges by that it will allocate a new Array on the Heap. If we always want that it should stay on the Stack we can use stackalloc (This only works for primitive types because objects are references)
"Span<Range> ranges = length < 1024 ? stackalloc Range[length] : new Range[length];"

We do a Split but this one works different than the Split on the String we get the Range of each split so we can access it on our span of the paths and convert that to a string (this will allocate a string on the Heap)
chars.Split(ranges, '|');

I also added a StringBuilder to avoid that we create a List and at the end just concat it to a string because we already have the values we want as a string at the end

**Comment by Flamifly** [comment]
Overall Spans are used to avoid allocations.
Allocations happen often at Strings (concat, substring, etc.) because strings are immutable and exist on the heap so everytime a new string will be allocated. With a Span you can do operations like Slice (Substring) which does not allocate something new instead you get a Span with the Pointers to your values and can work with them.
It's kinda the opposite of the StringBuilder it is not used to concat strings it is used to perform methods that would change the String which would result in an allocation

**Comment by Flamifly** [comment]
If you want to know more about Span you might should watch that;
https://www.youtube.com/watch?v=5KdICNWOfEQ

**Comment by Flamifly** [comment]
And because of the 1025 if you use stackalloc you should have a max size in my case I mostly use 1024

If you do not limit it you can end with a Stack overflow for example you wanted to create 100Milion things on the Stack which might not work good

**Comment by Flamifly** [comment]
Hope I explained it good enough if not just tell me

**Comment by FrozenAssassine** [comment]
Wow, thanks for the perfect explaination, I never really thought about spans. 
I knew they existed, but not for what purpose😂. 
Sounds like I have to learn more about them, especially for my custom textbox to replace some stuff like split, substring, remove etc. 

Nice to hear about it, I will dive deeper into it🤞

**Comment by finn-freitag** [comment]
Same for me, I've never used Spans before. I'll read more about it. Thanks!

**Comment by Flamifly** [comment]
If you want to dive deeper into it there are multiple Videos with Stephen Toub who explains it.
You also could take a look on his Performance Improvements for each .net Version like
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-8/#strings-arrays-and-spans

**Comment by Flamifly** [comment]
Here is an example how much better it can be in some cases
![image](https://github.com/user-attachments/assets/4f909e0a-01f3-43b9-a2d9-925fdf209279)

I can do the same with Spans without allocation and in this 20x better performance
